### PR TITLE
Update constants.js

### PR DESCRIPTION
**Pull request by krrisis**
changes in the text so that we're less spammy with links in public rooms

### CODE REVIEW

**Comment by krrisis** [comment]
hey @deamme or @FrederikBolding could you merge this one? thx!

**Comment by FrederikBolding** [comment]
I don't have permissions for merging in the repo or code review, but it looks good from here! 😄

**Comment by vojtechsimetka** [comment]
@krrisis done, someone may need to redeploy

**Comment by deamme** [comment]
@FrederikBolding you got it now :). @vojtechsimetka we got automatic deployments!

**Comment by FrederikBolding** [comment]
Thanks @deamme ! - And yes @vojtechsimetka its been deployed automatically! 😄 See: https://circleci.com/gh/Giveth/giveth-bot/43

**Pull request merged**
